### ISSUE TITLE
Can't compile on 4.26_ChaosPreview2

### ISSUE THREAD

**Issue by Theliraan** [hugoattal/DarkerNodes#141]
Hi!

Can't compile project with Unreal Engine 4.26_ChaosPreview2 (compiled from launcher) with marker nodes from marketplace (2.6 for 4.26.0). Compiler error:
`0>%PROJECT_PATH%/Plugins/DarkerNodes/Source/DarkerNodes/Private/Colorizer/ColorizerPanels.cpp(7): Error C1083 : Cannot open include file: 'EditorStyle/Private/SlateEditorStyle.cpp': No such file or directory`

**Comment by TheHerobrine** [comment]
@Theliraan Hum I haven't actually tested it with "4.26_ChaosPreview2" since it's not an official release, and I can't make it available directly in the marketplace...

I'll have a look, thank you for reporting it!

**Comment by Theliraan** [comment]
> @Theliraan Hum I haven't actually tested it with "4.26_ChaosPreview2" since it's not an official release, and I can't make it available directly in the marketplace...
> 
> I'll have a look, thank you for reporting it!

Ye, thank you for fast answer. I truly understand you - no problem here. Just if it's interest and available to you: please look a bit.

Now I can close ticket if you ask :)

**Comment by TheHerobrine** [comment]
So I downloaded the Chaos Preview 2, but I had no problem compiling it... Are you using a C++ based project or a BP base project 🤔 ?

**Comment by Theliraan** [comment]
> So I downloaded the Chaos Preview 2, but I had no problem compiling a project with Darker Nodes... Are you using a C++ based project or a BP base project 🤔 ?

C++ based

**Comment by TheHerobrine** [comment]
Weird... If it's not too much hassle, could please share me a minimum project that does not compile?

**Comment by Theliraan** [comment]
> Weird... If it's not too much hassle, could please share me a minimum project that does not compile?

Thanks for attention. Yes, I'll try to make new project with DarkerNodes (little bit later, have to work now, sorry :) )

**Comment by hugoattal** [comment]
I'm closing this, but if you come across this bug again, don't hesitate to reopen it!
